# Generated by Django 2.2.28 on 2022-12-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms_and_conditions', '0001_terms_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='termandcondition',
            name='type',
            field=models.CharField(default='DEFAULT', max_length=30),
        ),
    ]
